export function getDom(root = document) {
  const getById = (id) => root.getElementById(id);

  return {
    markdownEditor: getById("markdown-editor"),
    editorLineNumbers: getById("editor-line-numbers"),
    editorCurrentLine: getById("editor-current-line"),
    editorSelectionHighlights: getById("editor-selection-highlights"),
    editorSyntaxHighlight: getById("editor-syntax-highlight"),
    markdownPreview: getById("markdown-preview"),
    themeToggle: getById("theme-toggle"),
    restoreDefaultsButtons: root.querySelectorAll(".restore-defaults-button"),
    importFromFileButtons: root.querySelectorAll("#import-from-file"),
    newDocumentButtons: root.querySelectorAll(".new-document-button"),
    importFromGithubButton: getById("import-from-github"),
    importFromFolderButton: getById("import-from-folder"),
    folderTreeFilterInput: getById("folder-tree-filter-input"),
    createTagButton: getById("create-tag-button"),
    deleteTagButton: getById("delete-tag-button"),
    tagManagementSearch: getById("tag-management-search"),
    tagManagementList: getById("tag-management-list"),
    folderTreeFilterToggleButtons: root.querySelectorAll(".toggle-folder-tree-filter"),
    folderTreeExpandToggleButtons: root.querySelectorAll(".toggle-folder-tree-expanded"),
    folderTreePane: getById("folder-tree-pane"),
    folderTreeRoot: getById("folder-tree-root"),
    fileInput: getById("file-input"),
    folderInput: getById("folder-input"),
    exportMd: getById("export-md"),
    exportHtml: getById("export-html"),
    exportPdf: getById("export-pdf"),
    copyMarkdownButton: getById("copy-markdown-button"),
    dropzone: getById("dropzone"),
    closeDropzoneBtn: getById("close-dropzone"),
    syncToggleButtons: root.querySelectorAll(".sync-toggle-button"),
    editorPane: getById("markdown-editor"),
    previewPane: root.querySelector(".preview-pane"),
    readingTimeElement: getById("reading-time"),
    wordCountElement: getById("word-count"),
    charCountElement: getById("char-count"),
    statusTipElement: getById("status-tip"),
    graphZoomStatusElement: getById("graph-zoom-status"),
    graphZoomPercentElement: getById("graph-zoom-percent"),
    graphPointsStatusElement: getById("graph-points-status"),
    graphPointsCountElement: getById("graph-points-count"),
    editorTextpadStatusElement: getById("editor-textpad-status"),
    editorTotalLengthElement: getById("editor-total-length"),
    editorTotalLinesElement: getById("editor-total-lines"),
    editorCursorLineElement: getById("editor-cursor-line"),
    editorCursorColumnElement: getById("editor-cursor-column"),
    editorPositionLabelElement: getById("editor-position-label"),
    editorPositionValueElement: getById("editor-position-value"),
    graphControls: {
      zoomStatus: getById("graph-zoom-status"),
      zoomPercent: getById("graph-zoom-percent"),
      pointsStatus: getById("graph-points-status"),
      pointsCount: getById("graph-points-count"),
      viewCanvas: getById("graph-view-canvas"),
      viewClose: getById("graph-view-close"),
      resetDefaults: getById("graph-reset-defaults"),
      searchInput: getById("graph-search-input"),
      typeFilter: getById("graph-type-filter"),
      groupFilter: getById("graph-group-filter"),
      tagFilter: getById("graph-tag-filter"),
    },
  };
}
