export function createAppContext() {
  return {
    actions: {},
    constants: {
      RENDER_DELAY: 100,
      SCROLL_SYNC_DELAY: 10
    },
    dom: {
      document,
      window,
      markdownEditor: document.getElementById("markdown-editor"),
      editorLineNumbers: document.getElementById("editor-line-numbers"),
      editorCurrentLine: document.getElementById("editor-current-line"),
      editorSelectionHighlights: document.getElementById("editor-selection-highlights"),
      editorSyntaxHighlight: document.getElementById("editor-syntax-highlight"),
      markdownPreview: document.getElementById("markdown-preview"),
      themeToggle: document.getElementById("theme-toggle"),
      restoreDefaultsButtons: document.querySelectorAll(".restore-defaults-button"),
      importFromFileButtons: document.querySelectorAll("#import-from-file"),
      newDocumentButtons: document.querySelectorAll(".new-document-button"),
      importFromGithubButton: document.getElementById("import-from-github"),
      importFromFolderButton: document.getElementById("import-from-folder"),
      folderTreeFilterInput: document.getElementById("folder-tree-filter-input"),
      createTagButton: document.getElementById("create-tag-button"),
      deleteTagButton: document.getElementById("delete-tag-button"),
      tagManagementSearch: document.getElementById("tag-management-search"),
      tagManagementList: document.getElementById("tag-management-list"),
      folderTreeFilterToggleButtons: document.querySelectorAll(".toggle-folder-tree-filter"),
      folderTreeExpandToggleButtons: document.querySelectorAll(".toggle-folder-tree-expanded"),
      folderTreeRoot: document.getElementById("folder-tree-root"),
      fileInput: document.getElementById("file-input"),
      folderInput: document.getElementById("folder-input"),
      exportMd: document.getElementById("export-md"),
      exportHtml: document.getElementById("export-html"),
      exportPdf: document.getElementById("export-pdf"),
      copyMarkdownButton: document.getElementById("copy-markdown-button"),
      shareButton: document.getElementById("share-button"),
      dropzone: document.getElementById("dropzone"),
      closeDropzoneBtn: document.getElementById("close-dropzone"),
      syncToggleButtons: document.querySelectorAll(".sync-toggle-button"),
      editorPane: document.getElementById("markdown-editor"),
      previewPane: document.querySelector(".preview-pane"),
      readingTimeElement: document.getElementById("reading-time"),
      wordCountElement: document.getElementById("word-count"),
      charCountElement: document.getElementById("char-count"),
      statusTipElement: document.getElementById("status-tip"),
      graphZoomStatusElement: document.getElementById("graph-zoom-status"),
      graphZoomPercentElement: document.getElementById("graph-zoom-percent"),
      graphPointsStatusElement: document.getElementById("graph-points-status"),
      graphPointsCountElement: document.getElementById("graph-points-count"),
      editorTextpadStatusElement: document.getElementById("editor-textpad-status"),
      editorTotalLengthElement: document.getElementById("editor-total-length"),
      editorTotalLinesElement: document.getElementById("editor-total-lines"),
      editorCursorLineElement: document.getElementById("editor-cursor-line"),
      editorCursorColumnElement: document.getElementById("editor-cursor-column"),
      editorPositionLabelElement: document.getElementById("editor-position-label"),
      editorPositionValueElement: document.getElementById("editor-position-value")
    },
    selectors: {},
    services: {},
    state: {
      markdownRenderTimeout: null,
      syncScrollingEnabled: true,
      isEditorScrolling: false,
      isPreviewScrolling: false,
      scrollSyncTimeout: null,
      currentViewMode: "split",
      autoSelectFileEnabled: true,
      currentFolderTreeNodes: [],
      folderTreeFilterText: "",
      selectedFolderTreeTags: new Set(),
      currentFolderSortMode: "name-asc",
      showUnsupportedFolderFiles: false,
      isFolderOpen: false,
      previewHoveredLinkUrl: "",
      linkAutocompleteLayer: null,
      linkAutocompleteState: null
    }
  };
}
